# Generated by Django 3.2 on 2023-09-08 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230908_0108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutreceipt',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Checkout Receipts'},
        ),
        migrations.RemoveField(
            model_name='productsubcategory',
            name='category',
        ),
    ]
