# Generated by Django 3.2 on 2023-09-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230908_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutreceipt',
            name='receipt_sent_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='checkoutreceipt',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
