# Generated by Django 3.2 on 2023-08-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20230816_0543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='num_of_times_viewed',
            new_name='num_of_times_solid',
        ),
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
