# Generated by Django 3.2 on 2023-08-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
