# Generated by Django 3.2 on 2023-08-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='quantity',
        ),
    ]
