# Generated by Django 3.2 on 2023-08-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='checkout_datte',
            new_name='checkout_date',
        ),
    ]
