# Generated by Django 3.2 on 2023-09-05 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20230828_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'ordering': ['-checkout_date']},
        ),
        migrations.AddField(
            model_name='checkout',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checkout',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateTimeField(),
        ),
    ]
