# Generated by Django 3.2 on 2023-09-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_checkout_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateTimeField(null=True),
        ),
    ]
